services:
  
  webapp_crocuscms_local:
    image: webapp_crocuscms_local:1.0.0
    container_name: webapp_crocuscms_local
    build:
      context: .
    ports:
      - 80:80
      - 5173:5173
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - mysql_test
    links:
      - mysql
      - mysql_test
    networks:
      - network_webapp

  mysql:
    image: mysql:8.0.32
    container_name: mysql_crocuscms_local
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "crocuscms_local"
      MYSQL_USER: "crocuscms_local"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
    command: --authentication_policy=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_webapp

  mysql_test:
    image: mysql:8.0.32
    container_name: mysql_test_crocuscms_local
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "crocuscms_local_test"
      MYSQL_USER: "crocuscms_local_test"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
    command: --authentication_policy=mysql_native_password
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - network_webapp

#  smtp:
#    platform: linux/x86_64
#    image: mailhog/mailhog
#    container_name: smtp_crocuscms_local
#    logging:
#      driver: 'none'
#    ports:
#      - 8003:1025
#      - 8100:8025
#    networks:
#      - network_webapp

networks:
  network_webapp:

volumes:
  mysql_data:
  mysql_test_data:
