services:
  
  webapp_crocuscms_local:
    image: webapp_crocuscms_local:1.0.0
    container_name: webapp_crocuscms_local
    build:
      context: .
    ports:
      - 80:80
      - 5173:5173
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - network_webapp

  mysql:
    image: mysql:8.0.32
    container_name: mysql_crocuscms_local
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $${DB_PASSWORD}
      MYSQL_DATABASE: $${DB_DATABASE}
      MYSQL_USER: $${DB_USERNAME}
      MYSQL_PASSWORD: $${DB_PASSWORD}
      MYSQL_TCP_PORT: 3306
    command: --authentication_policy=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_webapp

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: smtp_crocuscms_local
    logging:
      driver: 'none'
    ports:
      - 8003:1025
      - 8100:8025
    networks:
      - network_webapp

networks:
  network_webapp:

volumes:
  mysql_data:
